# 이게뭐약 도커 컴포즈 yml
#   - 메인 서버 / DL 서버 (각 레포지터리 내 docker file)
#   - DB 서버 / HAProxy (컴포즈 파일 내 작성)
# 구조
#   - HAProxy - 메인 서버 - HAProxy - DL 서버
#   - 메인 서버는 LB 없이 DB와 연결
version: "3.8"

services:
  # 메인서버
  main:
    build: ../wip-main-server-v2
    container_name: wip-main-server-v2
    restart: always
      
    environment:
      - TZ=Asia/Seoul

    env_file:
      - ../wip-main-server-v2/.env

    volumes:
      - ../wip-main-server-v2/logs:/usr/local/wip-main-server-v2/logs
      - ../resources:/usr/local/resources

    depends_on:
      - db

    ports:
      - ${MAIN_SERVER_PORT}:${MAIN_SERVER_PORT}
      - 80:80

    networks:
      - wip-net


    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: continue
  
  # 딥러닝 서버
  dl:
    build: ../wip-deep-learning-server-v2
    container_name: wip-deep-learning-server-v2
    restart: always

    environment:
      - TZ=Asia/Seoul
    
    env_file:
      - ../wip-deep-learning-server-v2/.env

    depends_on:
      - main
      - db

    ports:
      - ${DL_SERVER_PORT}:${DL_SERVER_PORT}

    networks:
      - wip-net

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: continue

  # DBMS
  db:
    image: mongo:7.0.7
    container_name: wip-mongo
    restart: always

    environment:
      - TZ=Asia/Seoul
      - MONGO_INIT_DB_DATABASE=whatispill

    volumes:
      - wip-db:/var/lib/mongodb

    networks:
      - wip-net

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: continue

volumes:
  wip-db:

    
networks:
  wip-net:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/db'