# 이게뭐약 도커 컴포즈 yml
#   - 메인 서버 / DL 서버 (각 레포지터리 내 docker file)
#   - DB 서버 / HAProxy (컴포즈 파일 내 작성)
# 구조
#   - HAProxy - 메인 서버 - HAProxy - DL 서버
#   - 메인 서버는 LB 없이 DB와 연결
version: "3.8"

services:
  # 메인서버
  main:
    build: ../wip-main-server-v2
    container_name: main
    restart: always
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ../wip-main-server-v2/.env
    volumes:
      - ../wip-main-server-v2/logs:/usr/local/wip-main-server-v2/logs
      - ../resources:/usr/local/resources
    depends_on:
      - db
    network_mode: host
    extra_hosts:
      - 'dl:127.0.0.1'
      - 'db:127.0.0.1'
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: continue
  
  # 딥러닝 서버
  dl:
    build: ../wip-deep-learning-server-v2
    container_name: dl
    restart: always
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ../wip-deep-learning-server-v2/.env
    network_mode: host
    extra_hosts:
      - 'main:127.0.0.1'
      - 'db:127.0.0.1'
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: continue

  # DBMS
  db:
    image: mongo:7.0.7
    container_name: db
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MONGO_INIT_DB_DATABASE=whatispill
    volumes:
      - /var/lib/mongodb:/data/db
    network_mode: host
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: continue
